services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      -  sql_data:C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Data
      - .\scripts:C:\scripts
    networks:
      - spark-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile.windows
    ports:
      - "8501:8501"
    volumes:
      - .\app:C:\app
    depends_on:
      - sqlserver
    networks:
      - spark-network

networks:
  spark-network:
    driver: nat

volumes:
  sql_data: