services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_TCP=1433
    ports:
      - "1433:1433"
    volumes:
      - /sqlserver_data:/var/opt/mssql
      - ./scripts:/scripts
    networks:
      - spark_network
    security_opt:
      - "credentialspec=file://mssql.json"
    user: "ContainerAdministrator"
    command: 
      - "/bin/bash"
      - "-c"
      - |
        # Configura permisos
        chown -R mssql /var/opt/mssql &&
        chmod -R 777 /var/opt/mssql &&
        # Inicia SQL Server
        /opt/mssql/bin/sqlservr
  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "4000:4040"
    volumes:
      - ./app:/app
    networks:
      - spark_network
  app:
    build: .
    ports:
      - "8500:8500"
    volumes:
      - ./app:/app
    environment:
      - PYSPARK_PYTHON=python3
    depends_on:
      - sqlserver
      - spark
    networks:
      - spark_network
volumes:
 sql_data:
networks:
  spark_network:
    driver: bridge